// Datos extraídos de las mallas curriculares oficiales UCV Chimbote (PDFs)
export const mallasCurriculares = {
  "Administración de Empresas": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos de la Administración", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Costos y Presupuestos", "Cátedra Vallejo", "Economía", "Inglés II"],
    3: ["Creatividad e Innovación", "Gestión del Talento Humano", "Diseño Organizacional", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Matemática para las Finanzas", "Derecho Empresarial y Comercial", "Inteligencia de Mercados", "Inglés IV"],
    5: ["Estadística Aplicada a los Negocios", "Constitución y Derechos Humanos", "Marketing", "Contabilidad Financiera", "Inglés V"],
    6: ["Administración Financiera", "Marketing Estratégico", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Gerencia y Prospectiva Estratégica", "Finanzas para los Negocios", "Marketing Internacional", "Filosofía y Ética", "Inglés VII"],
    8: ["Desarrollo de Competencias Gerenciales", "Simuladores de Negocio", "Experiencia Curricular Electiva", "Gestión de Proyectos", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Administración y Negocios Internacionales": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos de Administración y Negocios Internacionales", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Comercio Internacional", "Cátedra Vallejo", "Economía", "Inglés II"],
    3: ["Creatividad e Innovación", "Legislación y Operatividad Aduanera", "Merceología, Nomenclatura y Clasificación Arancelaria", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Marketing", "Derecho de los Negocios Internacionales", "Matemática para las Finanzas", "Inglés IV"],
    5: ["Business Analytics", "Contabilidad y Finanzas", "International Market Research", "Constitución y Derechos Humanos", "Inglés V"],
    6: ["Costos y Cotizaciones Internacionales", "Gestión Financiera Internacional", "Inteligencia Artificial y Aprendizaje Automático", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Gestión de la Cadena de Suministro Internacional", "International Marketing", "International Sales Management", "Filosofía y Ética", "Inglés VII"],
    8: ["Gestión del Talento Humano", "International Business Plan", "Experiencia Curricular", "Electiva", "Gestión de Proyectos", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Arquitectura": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos en Arquitectura", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Historia y Teoría de la Arquitectura", "Cátedra Vallejo", "Expresión Gráfica", "Inglés II"],
    3: ["Creatividad e Innovación", "Dibujo Arquitectónico", "Topografía", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "El Hombre y su Contexto", "Modelamiento BIM en Edificaciones", "Orientación Estructural", "Inglés IV"],
    5: ["Arquitectura y Habilitación Urbana", "Accesibilidad y Diseño Universal", "Construcción I", "Constitución y Derechos Humanos", "Inglés V"],
    6: ["Arquitectura y Equipamiento Metropolitano", "Tecnología Ambiental I", "Acondicionamiento Territorial", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Ciudad y Patrimonio Histórico", "Construcción II", "Planificación Urbana, Desarrollo Territorial y Rural", "Filosofía y Ética", "Inglés VII"],
    8: ["Arquitectura e Intervención Urbana", "Tecnología Ambiental II", "Experiencia Curricular Electiva", "Gestión de Proyectos", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Arte & Diseño Gráfico Empresarial": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos del Arte & Diseño", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Cátedra Vallejo", "Tecnologías Emergentes y sus Aplicaciones", "Taller de Formas y Expresión", "Inglés II"],
    3: ["Inclusión y Accesibilidad", "Creatividad e Innovación", "Maquetación de Medios", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Teoría del Color", "Diseño Creativo", "Expresiones Artísticas y sus Contextos", "Inglés IV"],
    5: ["Constitución y Derechos Humanos", "Estudio Tipográfico", "Creación Gráfica Digital", "Semiótica Visual", "Inglés V"],
    6: ["Gestión de Identidad Corporativa", "Diseño Web", "Fotografía Socioeditorial", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Filosofía y Ética", "Animación Digital", "Emprendimiento y Gestión en Diseño", "Campaña Gráfica Publicitaria", "Inglés VII"],
    8: ["Diseño Multicanal", "Gestión de Proyectos", "Modelado Tridimensional", "Experiencia Curricular Electiva", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Ciencias de la Comunicación": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos de la Comunicación", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Tecnologías Emergentes y sus Aplicaciones", "Cátedra Vallejo", "Comunicación, Sociedad y Cultura", "Inglés II"],
    3: ["Inclusión y Accesibilidad", "Creatividad e Innovación", "Comunicación Corporativa", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Semiótica", "Sociología de la Comunicación", "Lenguaje Audiovisual y Cinematográfico", "Inglés IV"],
    5: ["Constitución y Derechos Humanos", "Periodismo Multimedial", "Diseño y Producción Publicitaria", "Fotografía", "Inglés V"],
    6: ["Taller de Guion Audiovisual", "Planeación Estratégica de la Comunicación Organizacional", "Comunicación para el Cambio Social", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Filosofía y Ética", "Diseño y Desarrollo de Proyectos de Comunicación para el Cambio Social", "Responsabilidad Social Corporativa", "Taller de Edición y Montaje", "Inglés VII"],
    8: ["Comunicación Digital y Gestión de Redes Sociales", "Producción Audiovisual Digital", "Experiencia Curricular Electiva", "Gestión de Proyectos", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Ciencias del Deporte": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos de la Ciencia del Rendimiento Humano", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Tecnologías Emergentes y sus Aplicaciones", "Cátedra Vallejo", "Administración Deportiva", "Inglés II"],
    3: ["Morfología Funcional Deportiva", "Creatividad e Innovación", "Teoría y Metodología del Entrenamiento", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Actividad Física Adaptada", "Deportes de Conjunto I", "Entrenamiento Deportivo", "Inglés IV"],
    5: ["Bioquímica del Deporte y la Actividad Física", "Constitución y Derechos Humanos", "Evaluación del Entrenamiento y Tecnología Aplicada", "Biomecánica y Cineantropometría", "Inglés V"],
    6: ["Fisiología del Esfuerzo Físico", "Preparación Física", "Deportes de Conjunto II", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Filosofía y Ética", "Medicina Deportiva", "Nutrición Aplicada al Deporte", "Pesas Olímpicas", "Inglés VII"],
    8: ["Tenis de Mesa", "Psicología Deportiva", "Experiencia Curricular Electiva", "Gestión de Proyectos", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Contabilidad": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos de Contabilidad", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Cátedra Vallejo", "Economía", "Contabilidad Empresarial", "Inglés II"],
    3: ["Creatividad e Innovación", "Administración", "Comercio Internacional", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Tributación", "Contabilidad Gubernamental", "Matemática para las Finanzas", "Inglés IV"],
    5: ["Normas Contables", "Tributación Aplicada", "Constitución y Derechos Humanos", "Costos y Presupuestos", "Inglés V"],
    6: ["Control Interno", "Planeamiento Tributario", "Costos Industriales", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Auditoría Financiera", "Finanzas", "Análisis e Interpretación de Estados Financieros", "Filosofía y Ética", "Inglés VII"],
    8: ["Auditoría Integral", "Tendencias en Contabilidad", "Experiencia Curricular Electiva", "Gestión de Proyectos", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Derecho": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos del Derecho y Sistema Jurídico", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Teoría General del Derecho", "Cátedra Vallejo", "Tecnologías Emergentes y sus Aplicaciones", "Inglés II"],
    3: ["Derecho Internacional Público", "Derecho Procesal Constitucional", "Derecho de Familia y Sucesiones", "Derecho Laboral", "Inglés IX"],
    4: ["Creatividad e Innovación", "Derecho Constitucional y Ciencia Política", "Inclusión y Accesibilidad", "Estadística y Análisis de Datos", "Inglés III"],
    5: ["Metodología de la Investigación Científica", "Derecho de Personas", "Derecho Administrativo", "Mecanismos Alternativos de Resolución de Conflictos", "Inglés IV"],
    6: ["Derecho Internacional Privado", "Argumentación Jurídica y Destrezas Legales", "Derecho Procesal Laboral", "Práctica Preliminar", "Inglés X"],
    7: ["Derecho Penal I", "Constitución y Derechos Humanos", "Acto Jurídico", "Derecho del Proceso Administrativo y Contencioso", "Inglés V"],
    8: ["Derecho Penal II", "Derechos Reales", "Derecho Tributario", "Experiencia Curricular Electiva", "Inglés VI"],
    9: ["Filosofía y Ética", "Derecho Procesal Penal", "Derecho de los Contratos y Obligaciones", "Derecho Corporativo I", "Inglés VII"],
    10: ["Derecho Procesal Civil", "Derecho Corporativo II", "Experiencia Curricular", "Electiva", "Gestión de Proyectos", "Inglés VIII"],
  },
  "Educación Inicial": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos de la Educación Inicial", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Cátedra Vallejo", "Tecnologías Emergentes y sus Aplicaciones", "Teorías de la Educación", "Inglés II"],
    3: ["Inclusión y Accesibilidad", "Creatividad e Innovación", "Desarrollo de la Conciencia Fonológica", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Desarrollo Psicológico y del Aprendizaje", "Neurodidáctica", "Enfoques Didácticos para la Enseñanza", "Inglés IV"],
    5: ["Constitución y Derechos Humanos", "Planificación Curricular", "Educación Inclusiva e Interculturalidad", "Transformación Digital", "Inglés V"],
    6: ["Educación y Atención Temprana", "Psicomotricidad para el Desarrollo del Niño", "Laboratorio del Pensamiento Científico en la Infancia", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Personal Social y Expresión Corporal", "Filosofía y Ética", "Didáctica de la Comunicación", "Gestión e Innovación en Instituciones Educativas", "Inglés VII"],
    8: ["Acompañamiento Pedagógico en Cunas", "Gestión de Proyectos", "Evaluación Educativa, Planes de Monitoreo y Asesoría en el Aula", "Experiencia Curricular Electiva", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Educación en Idiomas - Inglés": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos de la Educación del Idioma Inglés", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Tecnologías Emergentes y sus Aplicaciones", "Cátedra Vallejo", "Fonética y Fonología del Idioma Inglés", "Inglés II"],
    3: ["Creatividad e Innovación", "Inclusión y Accesibilidad", "Gramática del Idioma Inglés", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Pedagogía de la Diversidad y Neurodivergencia", "Pedagogy for Teaching English Language", "Written Comprehension in English - Reading", "Inglés IV"],
    5: ["Constitución y Derechos Humanos", "Oral Comprehension in English - Listening", "Gestión Curricular y Pedagógica para la Enseñanza del Inglés en Inicial y Primaria", "Producción de Materiales y Recursos para la Enseñanza del Inglés", "Inglés V"],
    6: ["Gestión Curricular y Pedagógica para la Enseñanza del Inglés en Secundaria", "Projects in the Classroom", "Written Production in English - Writing", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Didáctica de la Evaluación para el Aprendizaje del Inglés I", "Gestión Curricular y Pedagógica para la Enseñanza del Inglés en Adultos", "Gestión de Centros Formativos en Idiomas Extranjeros", "Filosofía y Ética", "Inglés VII"],
    8: ["Didáctica de la Evaluación para el Aprendizaje del Inglés II", "Oral Production in English - Speaking", "Gestión de Proyectos", "Experiencia Curricular Electiva", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Enfermería": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos de la Enfermería", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Cátedra Vallejo", "Biología Celular y Molecular", "Salud Pública", "Inglés II"],
    3: ["Creatividad e Innovación", "Nutrición", "Morfofisiología", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Microbiología y Parasitología", "Epidemiología", "Cuidado de Enfermería Básica", "Inglés IV"],
    5: ["Cuidado de Enfermería en Salud Mental y Psiquiatría", "Farmacología", "Cuidado de Enfermería en Salud del Adulto I", "Constitución y Derechos Humanos", "Inglés V"],
    6: ["Cuidado de Enfermería en Salud del Adulto II", "Cuidados Paliativos y Alternativos", "Cuidado de Enfermería en Salud de la Mujer y Recién Nacido", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Cuidado de Enfermería en Salud del Niño y Adolescente I", "Cuidado de Enfermería en Salud Familiar y Comunitaria", "Gestión en Servicios de Salud", "Filosofía y Ética", "Inglés VII"],
    8: ["Cuidado de Enfermería en Salud del Niño y Adolescente II", "Enfermería en Emergencias y Desastres", "Experiencia Curricular Electiva", "Gestión de Proyectos", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Internado I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Internado II", "Inglés X"],
  },
  "Ingeniería Ambiental": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos en Ingeniería Ambiental", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Química Orgánica e Inorgánica", "Cátedra Vallejo", "Expresión Gráfica", "Inglés II"],
    3: ["Creatividad e Innovación", "Biología y Ecología", "Matemática para la Ingeniería", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Física General", "Cálculo Integral y Ecuaciones Diferenciales", "Química Analítica y Ambiental", "Inglés IV"],
    5: ["Gestión y Tratamiento de Suelos", "Constitución y Derechos Humanos", "Gestión de Riesgos Ambientales y Desastres", "Accesibilidad y Diseño Universal", "Inglés V"],
    6: ["Gestión y Tratamiento de la Contaminación Atmosférica", "Gestión y Tratamiento de Aguas", "Sistema de Gestión Integrado y Política Ambiental", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Filosofía y Ética", "Evaluación de Impacto Ambiental", "Gestión y Tratamiento de los Residuos Sólidos", "Monitoreo Ambiental y Resolución de Conflicto", "Inglés VII"],
    8: ["Biotecnología y Remediación Ambiental", "Cartografía y Aplicaciones Geoespacial", "Experiencia Curricular Electiva", "Gestión de Proyectos", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Ingeniería Civil": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos en Ingeniería Civil", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Tecnología del Concreto y Materiales", "Cátedra Vallejo", "Expresión Gráfica", "Inglés II"],
    3: ["Creatividad e Innovación", "Topografía y Geodesia", "Matemática para la Ingeniería", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Cálculo Integral y Ecuaciones Diferenciales", "Física General", "Mecánica de Suelos", "Inglés IV"],
    5: ["Accesibilidad y Diseño Universal", "Mecánica Estructural", "Caminos y Pavimentos", "Constitución y Derechos Humanos", "Inglés V"],
    6: ["Mecánica de Fluidos e Hidráulica", "Análisis Estructural", "Ingeniería de Transportes y Diseño Vial", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Ingeniería Sanitaria", "Ingeniería de la Construcción", "Diseño de Concreto Armado", "Filosofía y Ética", "Inglés VII"],
    8: ["Ingeniería de Obras Hidráulicas", "BIM Aplicado a Obras Civiles", "Experiencia Curricular Electiva", "Gestión de Proyectos", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Ingeniería Industrial": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos en Ingeniería Industrial", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Química General", "Cátedra Vallejo", "Expresión Gráfica", "Inglés II"],
    3: ["Creatividad e Innovación", "Economía y Finanzas", "Matemática para la Ingeniería", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Cálculo Integral y Ecuaciones Diferenciales", "Física General", "Contabilidad Gerencial y Costos", "Inglés IV"],
    5: ["Accesibilidad y Diseño Universal", "Estudio del Trabajo", "Investigación de Operaciones", "Constitución y Derechos Humanos", "Inglés V"],
    6: ["Simulación e Inteligencia de Datos", "Tecnología y Sistemas de Producción", "Ergonomía, Seguridad y Salud Ocupacional", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Dirección Táctica de Operaciones", "Logística Integrada y Cadena de Suministro", "Filosofía y Ética", "Inglés VII"],
    8: ["Dirección Estratégica de Operaciones", "Sistemas Integrados de Gestión", "Experiencia Curricular Electiva", "Gestión de Proyectos", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Prácticas Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Prácticas Preprofesional II", "Inglés X"],
  },
  "Ingeniería de Sistemas": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos en Ingeniería de Sistemas", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Algoritmos y Programación", "Cátedra Vallejo", "Expresión Gráfica", "Inglés II"],
    3: ["Creatividad e Innovación", "Fundamentos de Modelado y Animación", "Matemática para la Ingeniería", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Cálculo Integral y Ecuaciones Diferenciales", "Física General", "Programación Orientada a Objetos", "Inglés IV"],
    5: ["Accesibilidad y Diseño Universal", "Constitución y Derechos Humanos", "Gestión de Datos e Información", "Redes Inalámbricas y Telefonía IP", "Inglés V"],
    6: ["Ingeniería de Software", "Administración de Servidores Multiplataforma", "Inteligencia de Negocios", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Filosofía y Ética", "Machine Learning", "Ciberseguridad", "Tecnología Web y Cloud Computing", "Inglés VII"],
    8: ["Patrones de Diseño de Realidad Virtual", "Programación de Aplicaciones Móviles", "Experiencia Curricular Electiva", "Gestión de Proyectos", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Práctica Preprofesional I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Práctica Preprofesional II", "Inglés X"],
  },
  "Psicología": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos de la Psicología", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Cátedra Vallejo", "Salud Pública", "Bases Biológicas del Comportamiento", "Inglés II"],
    3: ["Creatividad e Innovación", "Psicología de las Organizaciones", "Psicología del Desarrollo", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Epidemiología", "Psicología Educativa", "Técnicas de la Entrevista y la Observación Psicológica", "Inglés IV"],
    5: ["Constitución y Derechos Humanos", "Técnicas Proyectivas", "Neuropsicología", "Psicología Clínica", "Inglés V"],
    6: ["Programas de Promoción, Prevención e Intervención en Psicología", "Pruebas Psicométricas para Niños", "Psicopatología", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Pruebas Psicométricas para Adultos", "Diagnóstico e Informe Psicológico", "Filosofía y Ética", "Psicología Experimental", "Inglés VII"],
    8: ["Gestión de Proyectos", "Prácticas Departamentales I", "Psicoterapia Individual", "Experiencia Curricular Electiva", "Inglés VIII"],
    9: ["Psicoterapia de Grupo y de Familia", "Psicometría", "Evaluación y Selección de Personas", "Prácticas Departamentales II", "Inglés IX"],
    10: ["Trabajo de Investigación I", "Internado I", "Inglés X"],
  },
  "Tecnología Médica en Laboratorio Clínico y Anatomía Patológica": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos de Laboratorio Clínico", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Cátedra Vallejo", "Salud Pública", "Química Inorgánica y Orgánica", "Inglés II"],
    3: ["Creatividad e Innovación", "Biología Celular", "Morfofisiología", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Bioquímica y Biología Molecular", "Histología y Embriología", "Epidemiología", "Inglés IV"],
    5: ["Constitución y Derechos Humanos", "Hematología y Hemostasia", "Bioquímica Clínica", "Citogenética Humana", "Inglés V"],
    6: ["Inmunología", "Bacteriología y Virología", "Experiencia Curricular Electiva", "Laboratorio Clínico", "Inglés VI"],
    7: ["Filosofía y Ética", "Micología y Parasitología", "Técnicas en Anatomía Patológica", "Farmacología y Toxicología", "Inglés VII"],
    8: ["Hematología Clínica y Medicina Transfusional", "Citopatología", "Gestión de Proyectos", "Experiencia Curricular Electiva", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Internado I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Internado II", "Inglés X"],
  },
  "Tecnología Médica en Terapia Física y Rehabilitación": {
    1: ["Pensamiento Lógico", "Habilidades Comunicativas", "Objetivos de Desarrollo Sostenible", "Fundamentos de la Terapia Física y Rehabilitación", "Inglés I"],
    2: ["Cambio Climático y Gestión de Riesgos", "Cátedra Vallejo", "Salud Pública", "Biología Celular y Molecular", "Inglés II"],
    3: ["Creatividad e Innovación", "Química y Principios de Bioquímica", "Biofísica", "Estadística y Análisis de Datos", "Inglés III"],
    4: ["Metodología de la Investigación Científica", "Epidemiología", "Morfofisiología", "Biomecánica", "Inglés IV"],
    5: ["Constitución y Derechos Humanos", "Fisiopatología", "Desarrollo Psicomotor", "Fisioterapia Musculoesquelética I", "Inglés V"],
    6: ["Fisioterapia en Salud Mental y Discapacidad", "Semiología Fisioterapéutica", "Fisioterapia Musculoesquelética lI", "Experiencia Curricular Electiva", "Inglés VI"],
    7: ["Filosofía y Ética", "Fisioterapia en Pediatría", "Fisioterapia Cardiorespiratoria", "Fisioterapia en Neurología y Adulto Mayor", "Inglés VII"],
    8: ["Fisiología del Ejercicio y Fisioterapia en Deportes", "Gestión de los Servicios de Terapia Física y Rehabilitación", "Gestión de Proyectos", "Experiencia Curricular Electiva", "Inglés VIII"],
    9: ["Trabajo de Investigación I", "Internado I", "Inglés IX"],
    10: ["Trabajo de Investigación II", "Internado II", "Inglés X"],
  },
};

// Helper: obtener todos los cursos de una carrera (aplanado)
export function getCursosPorCarrera(carrera) {
  const malla = mallasCurriculares[carrera];
  if (!malla) return [];
  return Object.values(malla).flat();
}

// Helper: obtener ciclos disponibles para una carrera
export function getCiclosPorCarrera(carrera) {
  const malla = mallasCurriculares[carrera];
  if (!malla) return [];
  return Object.keys(malla).map(Number).sort((a, b) => a - b);
}

// Helper: obtener cursos de un ciclo específico
export function getCursosPorCiclo(carrera, ciclo) {
  const malla = mallasCurriculares[carrera];
  if (!malla || !malla[ciclo]) return [];
  return malla[ciclo];
}