spring.profiles.active=dev

# Configuración del servidor
server.port=8080

# Configuración JWT
jwt.secret=mentorlink_secret_key_2024_seguridad_jwt_token_32chars
jwt.expiration=86400000

spring.jackson.serialization.fail-on-empty-beans=false

# Configuración de logging
logging.level.org.springframework.security=DEBUG
logging.level.com.mentorlink=DEBUG
